name: NPM Package Sync
 
on:
  push:
    branches: [ main ]
 
jobs:
  sync-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
